name: CI Build Update
on:
  push:
    branches: ["main"]

jobs:
  Demo_Hello:
      runs-on: ubuntu-latest

  steps:
    - name: code checkout
      uses: actions/checkout@v4

    - name:  Print Hello from GitHub Actions!
      run: echo "Hello from GitHub Actions!"

    

