name: CI Build Update
  on:
    push:
      branches:["main"]

  job:
    Demo Hello:
      runs-on: ubunt-latest

    steps:
      - name: code checkout
        uses: action/checkout@v4

      - name:  Print Hello from GitHub Actions!
        runs: echo "Hello from GitHub Actions!"

    

