# Goal: Whenever someone changes python code ,
# the Linter will chack if the syntax , format , intentation (linting) is correct or not .

name: Auto Linter

on: 
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
    # This step will automatically clone the code of the current branch into the runner
      - name: checkout/clone the code
        uses: actions/checkout@v7
    # This step will install the linting tool
      - name: install linter
        run: pip install ruff
    # This step will run the linter
      - name: check the file from linting
        run: ruff check .
