name: PR Check

on:
  pull_request:
    branches:
      - feature/pr-check-test 
    types:
      - opened
      - synchronize

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: PR check running for branch
              run: echo "PR check running for branch ${{ github.head_ref }}"
